config/routes.rb
HotFeed::Application.routes.draw do
  root 'feeds#index'

  get '/entertainment', :to => 'feeds#entertainment'

  get '/diy', :to => 'feeds#diy'

  get '/animal', :to => 'feeds#animal'

  get '/rewind', :to => 'feeds#rewind'

  get '/politics', :to => 'feeds#politics'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :links

  def pop_it_like_its_hot(hot_list)
    hot_list.pop
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :feed
end

app/models/scraper.rb
require 'open-uri'

class Scraper < ActiveRecord::Base
  
  def open_url(route)
    Nokogiri::HTML(open("http://www.buzzfeed.com/#{route}"))
  end

  def generate_links_array_helper(feed, route)
    return self.generate_links_array(route,"div.hot-item a.hot-headline") if feed.id == 1 # Feed1 always = hot, unique css path
    return self.generate_links_array(route,"h2#test a") if feed.id == 2 # Feed2 always = entertainment, unique css path
    return self.generate_links_array(route,"div.thumb-unit a") if feed.id >= 3 && feed.id <= 6 # lump together feeds that fit into thumb-unit css path
  end

  def generate_links_array(route, css_path)
    self.open_url(route).css(css_path).collect do |link|
      if link.attr("href").include?("http")
        link.attr("href")
      else
        "http://www.buzzfeed.com#{link.attr("href")}"
      end
    end
  end

  def assign_links_to_feed(feed, route)
    feed.links.destroy_all
    generate_links_array_helper(feed, route).each do |link|
      Link.where(path: link, feed_id: feed.id).first_or_create
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
#TODO: DRY Actions
#TODO: fix view problem, check it out on index.html.erb

class FeedsController < ApplicationController
  before_action :set_feed, only: [ :show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feed = Feed.where(id: 1).first_or_create
    if @feed.links.length == 0 || ((Time.now - @feed.links.first.created_at) >= 2700)
      Scraper.new.assign_links_to_feed(@feed, 'hot')
      redirect_to action: 'index'
    end 
    if !session[:hot_list] || session[:hot_list].length == 0
      session[:hot_list] = @feed.links.shuffle
    end
  end

  def entertainment
    @feed = Feed.where(id: 2).first_or_create
    if @feed.links.length == 0 || ((Time.now - @feed.links.first.created_at) >= 2700)
      Scraper.new.assign_links_to_feed(@feed, 'entertainment')
      redirect_to action: 'entertainment'
    end 
    if !session[:entertain_list] || session[:entertain_list].length == 0
      session[:entertain_list] = @feed.links.shuffle
    end
  end

  def animal
    @feed = Feed.where(id: 3).first_or_create
    if @feed.links.length == 0 || ((Time.now - @feed.links.first.created_at) >= 2700)
      Scraper.new.assign_links_to_feed(@feed, 'animals')
      redirect_to action: 'animal'
    end 
    if !session[:animal_list] || session[:animal_list].length == 0
      session[:animal_list] = @feed.links.shuffle
    end
  end

  def diy
    @feed = Feed.where(id: 4).first_or_create
    if @feed.links.length == 0 || ((Time.now - @feed.links.first.created_at) >= 2700)
      Scraper.new.assign_links_to_feed(@feed, 'diy')
      redirect_to action: 'diy'
    end 
    if !session[:diy_list] || session[:diy_list].length == 0
      session[:diy_list] = @feed.links.shuffle
    end
  end

  def rewind
    @feed = Feed.where(id: 5).first_or_create
    if @feed.links.length == 0 || ((Time.now - @feed.links.first.created_at) >= 2700)
      Scraper.new.assign_links_to_feed(@feed, 'rewind')
      redirect_to action: 'rewind'
    end 
    if !session[:rewind_list] || session[:rewind_list].length == 0
      session[:rewind_list] = @feed.links.shuffle
    end
  end

  def politics
    @feed = Feed.where(id: 6).first_or_create
    if @feed.links.length == 0 || ((Time.now - @feed.links.first.created_at) >= 2700)
      Scraper.new.assign_links_to_feed(@feed, 'politics')
      redirect_to action: 'politics'
    end 
    if !session[:politics_list] || session[:politics_list].length == 0
      session[:politics_list] = @feed.links.shuffle
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feed }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params[:feed]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/animal.html.erb
<div class="col-lg-8 col-lg-offset-1">
  <div class="col-md-8 col-md-offset-3">
    <button type="button" class="btn btn-default btn-lg btn-block" id="refresh-button"> next, please </button>
  </div>

  <br>
  <div id="hot-div">

    <br>
    <br>
    <br>
      
    <iframe src=<%= @feed.pop_it_like_its_hot(session[:animal_list]).path %> width="1100" height="700"></iframe>
    <% if session[:animal_list].length == 0 %>
      <% session[:animal_list] = @feed.links.shuffle %>
    <% end %>
  </div>
</div>

app/views/feeds/diy.html.erb
<div class="col-lg-8 col-lg-offset-1">
  <div class="col-md-8 col-md-offset-3">
    <button type="button" class="btn btn-default btn-lg btn-block" id="refresh-button"> next, please </button>
  </div>
  <br>
  <div id="hot-div">

    <br>
    <br>
    <br>
      
    <iframe src=<%= @feed.pop_it_like_its_hot(session[:diy_list]).path %> width="1100" height="700"></iframe>
    <% if session[:diy_list].length == 0 %>
      <% session[:diy_list] = @feed.links.shuffle %>
    <% end %>
  </div>
</div>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/entertainment.html.erb
<div class="col-lg-8 col-lg-offset-1">
  <div class="col-md-8 col-md-offset-3">
    <button type="button" class="btn btn-default btn-lg btn-block" id="refresh-button"> next, please </button>
  </div>
  <br>
  <div id="hot-div">

    <br>
    <br>
    <br>
      
    <iframe src=<%= @feed.pop_it_like_its_hot(session[:entertain_list]).path %> width="1100" height="700"></iframe>
    <% if session[:entertain_list].length == 0 %>
      <% session[:entertain_list] = @feed.links.shuffle %>
    <% end %>
  </div>
</div>

app/views/feeds/index.html.erb
<div class="col-lg-8 col-lg-offset-1">
  <div class="col-md-8 col-md-offset-3">
    <button type="button" class="btn btn-default btn-lg btn-block" id="refresh-button"> next, please </button>
  </div>
  <br>
  <div id="hot-div">

    <br>
    <br>
    <br>
      
    <iframe src=<%= @feed.pop_it_like_its_hot(session[:hot_list]).path %> width="1100" height="700"></iframe>
    <% if session[:hot_list].length == 0 %>
      <% session[:hot_list] = @feed.links.shuffle %>
    <% end %>
  </div>
</div>

<!-- TODO: because of the logic on lines 13-15, the last link in the session[:hot_list] array may never be displayed. Look into this (true of each feed view) -->

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/politics.html.erb
<div class="col-lg-8 col-lg-offset-1">
  <div class="col-md-8 col-md-offset-3">
    <button type="button" class="btn btn-default btn-lg btn-block" id="refresh-button"> next, please </button>
  </div>
  <br>
  <div id="hot-div">

    <br>
    <br>
    <br>
      
    <iframe src=<%= @feed.pop_it_like_its_hot(session[:politics_list]).path %> width="1100" height="700"></iframe>
    <% if session[:politics_list].length == 0 %>
      <% session[:politics_list] = @feed.links.shuffle %>
    <% end %>
  </div>
</div>

app/views/feeds/rewind.html.erb
<div class="col-lg-8 col-lg-offset-1">
  <div class="col-md-8 col-md-offset-3">
    <button type="button" class="btn btn-default btn-lg btn-block" id="refresh-button"> next, please </button>
  </div>
  <br>
  <div id="hot-div">

    <br>
    <br>
    <br>
      
    <iframe src=<%= @feed.pop_it_like_its_hot(session[:rewind_list]).path %> width="1100" height="700"></iframe>
    <% if session[:rewind_list].length == 0 %>
      <% session[:rewind_list] = @feed.links.shuffle %>
    <% end %>
  </div>
</div>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>HotFeed</title>
     <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
     <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <script type="text/javascript">

     
     var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23019901-1']);
      _gaq.push(['_setDomainName', "bootswatch.com"]);
        _gaq.push(['_setAllowLinker', true]);
      _gaq.push(['_trackPageview']);

     (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

    </script>
  </head>
  <body>
    <script src="../assets/js/bsa.js"></script>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
            
          <h2 id="site-name"><%= link_to 'HotFeed', root_path  %></h2>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <li>
                <a href="/" class="break-hover"></a>
              </li>
              
          
              <li>
                <%= link_to 'Entertainment', entertainment_path, class: "entertainment"%>
              </li>
              <li>
                <%= link_to 'Animals', animal_path, class: "animal"%>
              </li>
              <li>
                <%= link_to 'DIY', diy_path, class: "diy"%>
              </li>
              <li>
                <%= link_to 'Rewind', rewind_path, class: "rewind"%>
              </li>
              <li>
                <%= link_to 'Politics', politics_path, class: "politics"%>
              </li>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <br>
            <br>
            <li>stay entertained.</li>
          </ul>

        </div>
      </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>


<%= yield %>

</body>
</html>